
PEOPLE_STATUSES = ["Candidate", "Employee"]
BOOKING_STATUSES = ["Pending", "Booked", "Completed", "Cancelled"]
PATIENT_STATUSES = ["Pending", "In Progress", "Completed", "Cancelled"]

TEMPLATES = {
    "People": {
        "key": "People",
        "label": "People (Candidates/Employees)",
        "keywords": [
            "firstname",
            "surname",
            "employee",
            "candidate",
            "dob",
            "email",
            "gender",
        ],
        "fields": [
            {
                "key": "type",
                "label": "Type",
                "required": True,
                "allowed": PEOPLE_STATUSES,
                "is_pii": False,
                "identifier": False,
                "synonyms": [
                    "candidate type",
                    "employee type",
                    "person type",
                    "role type",
                ],
                "pattern": "enum",
                "description": "The category of the person record.",
                "examples": ["Candidate", "Employee"],
            },
            {
                "key": "id",
                "label": "Candidate/Employee No",
                "required": True,
                "allowed": None,
                "is_pii": True,
                "identifier": True,
                "synonyms": [
                    "employee no",
                    "employee number",
                    "candidate number",
                    "emp no",
                    "emp#",
                    "person id",
                ],
                "pattern": "integer",
                "sequence": "+1",
                "description": "The unique numeric identifier for the candidate or employee.",
                "examples": ["1001", "54022", "883"],
            },
            {
                "key": "title",
                "label": "Title",
                "required": True,
                "allowed": ["Mr", "Ms", "Mrs", "Miss", "Dr"],
                "is_pii": True,
                "identifier": False,
                "synonyms": ["salutation", "honorific"],
                "normalize": "titlecase",
                "description": "The person's salutation or title.",
                "examples": ["Mr", "Mrs", "Dr", "Ms"],
            },
            {
                "key": "firstName",
                "label": "First Name",
                "required": True,
                "allowed": None,
                "is_pii": True,
                "identifier": False,
                "synonyms": ["firstname", "given name", "forename", "name first"],
                "normalize": "titlecase",
                "description": "The person's given name.",
                "examples": ["John", "Sarah", "Michael"],
            },
            {
                "key": "surname",
                "label": "Surname",
                "required": True,
                "allowed": None,
                "is_pii": True,
                "identifier": False,
                "synonyms": ["last name", "family name", "lastname"],
                "normalize": "titlecase",
                "description": "The person's family name or surname.",
                "examples": ["Smith", "Jones", "O'Connor"],
            },
            {
                "key": "gender",
                "label": "Gender",
                "required": True,
                "allowed": ["M", "F", "Male", "Female", "Other"],
                "is_pii": True,
                "identifier": False,
                "synonyms": ["sex"],
                "pattern": "enum",
                "description": "The biological sex or gender identity.",
                "examples": ["M", "F", "Male", "Female"],
            },
            {
                "key": "dob",
                "label": "DOB",
                "required": True,
                "allowed": None,
                "is_pii": True,
                "identifier": False,
                "synonyms": ["date of birth", "birthdate", "birth date"],
                "pattern": "date",
                "dateFormat": "DD-MM-YYYY",
                "description": "The person's date of birth.",
                "examples": ["25-12-1980", "01-05-1995"],
            },
            {
                "key": "email",
                "label": "Email",
                "required": True,
                "allowed": None,
                "is_pii": True,
                "identifier": False,
                "synonyms": ["email address", "e-mail", "mail"],
                "pattern": "email",
                "normalize": "email",
                "description": "The person's contact email address.",
                "examples": ["john.smith@example.com", "sarah.j@company.org"],
            },
        ],
    },
    "Bookings": {
        "key": "Bookings",
        "label": "Bookings (Assessment Appointments)",
        "keywords": [
            "booking",
            "appointment",
            "assessment",
            "date",
            "time",
            "location",
            "clinic",
            "provider",
        ],
        "fields": [
            {
                "key": "bookingRef",
                "label": "Booking Reference",
                "required": True,
                "allowed": None,
                "is_pii": False,
                "identifier": True,
                "synonyms": ["booking ref", "booking id", "appt ref", "reference", "ref"],
                "pattern": "string",
                "description": "Unique identifier for the booking appointment.",
                "examples": ["BK-1001", "APT-992"],
            },
            {
                "key": "personNumber",
                "label": "Candidate/Employee No",
                "required": True,
                "allowed": None,
                "is_pii": True,
                "identifier": True,
                "synonyms": [
                    "employee no",
                    "person no",
                    "candidate no",
                    "emp no",
                    "emp#",
                    "person id",
                ],
                "pattern": "relationship",
                "relationship": {
                    "targetTemplate": "People",
                    "targetField": "id"
                },
                "description": "Numeric ID of the person being assessed.",
                "examples": ["1001", "54022"],
            },
            {
                "key": "assessmentName",
                "label": "Assessment Name",
                "required": True,
                "allowed": None,
                "is_pii": False,
                "identifier": False,
                "synonyms": ["assessment", "exam name", "panel", "service"],
                "normalize": "titlecase",
                "description": "Text, Title Case",
            },
            {
                "key": "assessmentDate",
                "label": "Assessment Date",
                "required": True,
                "allowed": None,
                "is_pii": False,
                "identifier": False,
                "synonyms": ["appt date", "booking date", "date"],
                "pattern": "date",
                "dateFormat": "DD-MM-YYYY",
                "description": "The date the assessment took place.",
                "examples": ["25-12-2025", "01-05-2026"],
            },
            {
                "key": "locationName",
                "label": "Location",
                "required": True,
                "allowed": None,
                "is_pii": False,
                "identifier": False,
                "synonyms": ["clinic", "site", "venue", "location"],
                "normalize": "titlecase",
                "description": "Text, Title Case",
            },
            {
                "key": "providerName",
                "label": "Provider Name",
                "required": True,
                "allowed": None,
                "is_pii": False,
                "identifier": False,
                "synonyms": ["provider", "doctor", "clinician", "supplier"],
                "normalize": "titlecase",
                "description": "Text, Title Case",
            },
            {
                "key": "status",
                "label": "Booking Status",
                "required": False,
                "allowed": BOOKING_STATUSES,
                "is_pii": False,
                "identifier": False,
                "synonyms": ["status", "booking status", "appt status"],
                "pattern": "enum",
                "description": "The current status of the booking.",
            },
        ],
    },
    "PatientData": {
        "key": "PatientData",
        "label": "Patient Data",
        "keywords": ["patient", "candidate", "employee", "assessment", "test", "block", "status", "notes"],
        "fields": [
            {
                "key": "patientId",
                "label": "Candidate/Employee No",
                "required": True,
                "allowed": None,
                "is_pii": True,
                "identifier": True,
                "synonyms": [
                    "employee no",
                    "employee number",
                    "candidate number",
                    "patient number",
                    "emp no",
                    "emp#",
                ],
                "pattern": "relationship",
                "relationship": {
                    "targetTemplate": "People",
                    "targetField": "id"
                },
                "sequence": "+1",
                "description": "Unique numeric ID for the patient.",
                "examples": ["1001", "54022"],
            },
            {
                "key": "assessmentName",
                "label": "Assessment Name",
                "required": True,
                "allowed": None,
                "is_pii": False,
                "identifier": False,  # Part of composite key with patientId
                "synonyms": ["assessment", "exam name", "panel", "service"],
                "normalize": "titlecase",
                "description": "Text, Title Case",
            },
            {
                "key": "blockName",
                "label": "Block",
                "required": False,
                "allowed": None,
                "is_pii": False,
                "identifier": False,
                "synonyms": ["block", "panel", "stream", "section"],
                "normalize": "titlecase",
                "description": "The block or stream (optional).",
                "examples": ["Block A", "Stream 1"],
            },
            {
                "key": "tests",
                "label": "Tests",
                "required": True,
                "allowed": None,
                "is_pii": False,
                "identifier": False,
                "synonyms": ["tests", "test panel", "procedures", "services"],
                "normalize": "titlecase",
                "description": "Text, Title Case",
            },
            {
                "key": "status",
                "label": "Status",
                "required": True,
                "allowed": ["Pending", "In Progress", "Completed", "Cancelled"],
                "is_pii": False,
                "identifier": False,
                "synonyms": ["status", "result status", "progress"],
                "pattern": "enum",
                "description": "The current status of the assessment.",
            },
            {
                "key": "notes",
                "label": "Clinical Notes",
                "required": False,
                "allowed": None,
                "is_pii": True,
                "identifier": False,
                "synonyms": ["notes", "comments", "clinical notes", "remarks"],
                "description": "Any clinical remarks or comments.",
                "examples": ["Patient arrived late", "Requires follow-up"],
            },
        ],
    },
}
